// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYNe0r4vnWcjHjC1EpSb2K_9a3YgNopg0',
    appId: '1:588004312825:web:73716bdb845611f9b3c428',
    messagingSenderId: '588004312825',
    projectId: 'fir-masterclass-549ba',
    authDomain: 'fir-masterclass-549ba.firebaseapp.com',
    storageBucket: 'fir-masterclass-549ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGK3uhBmybHKMvm-n2y29byEote84v8Cc',
    appId: '1:588004312825:android:7af7841f386fd253b3c428',
    messagingSenderId: '588004312825',
    projectId: 'fir-masterclass-549ba',
    storageBucket: 'fir-masterclass-549ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYkIQrxFeQEseGZ9ZXsRpNtaTBSZU9gzk',
    appId: '1:588004312825:ios:6b572f48c20b0a62b3c428',
    messagingSenderId: '588004312825',
    projectId: 'fir-masterclass-549ba',
    storageBucket: 'fir-masterclass-549ba.appspot.com',
    iosBundleId: 'com.example.flutterRpg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYkIQrxFeQEseGZ9ZXsRpNtaTBSZU9gzk',
    appId: '1:588004312825:ios:6b572f48c20b0a62b3c428',
    messagingSenderId: '588004312825',
    projectId: 'fir-masterclass-549ba',
    storageBucket: 'fir-masterclass-549ba.appspot.com',
    iosBundleId: 'com.example.flutterRpg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYNe0r4vnWcjHjC1EpSb2K_9a3YgNopg0',
    appId: '1:588004312825:web:b9179f846ca4918db3c428',
    messagingSenderId: '588004312825',
    projectId: 'fir-masterclass-549ba',
    authDomain: 'fir-masterclass-549ba.firebaseapp.com',
    storageBucket: 'fir-masterclass-549ba.appspot.com',
  );
}
